version: "3.8"
services:
 backend:
  container_name: backend
  image: back_sas_img:1
  build:
   context: ..
   dockerfile: ./kw1_BingChilling_Infrastructure/dockerfiles/backend_multistage_dockerfile
  ports:
   - 8080:8080
  depends_on:
   - mysql
  networks:
   - sas_network
  restart: always
 mysql:
  image: mysql:8.0.33
  container_name: dbserver
  environment:
   - MYSQL_ROOT_PASSWORD=123
   - LANG="en_US.UTF-8"
   - TZ="UTC"
   - MYSQL_USER=dev1
   - MYSQL_PASSWORD=123
   - MYSQL_DATABASE=sqlserversas
  volumes:
   - /sas/mysql:/var/lib/mysql
  networks:
   - sas_network
  ports:
   - 3306:3306
  restart: always
 frontend:
  container_name: frontend
  image: front_sas_img:1
  build:
   context: ..
   dockerfile: ./kw1_BingChilling_Infrastructure/dockerfiles/frontend_multistage_dockerfile
  ports:
   - 80:80
  depends_on:
   - backend
  restart: always
networks:
  sas_network:
  
