name: Deploy to VPN Server

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: linux
    steps:
      - uses: actions/checkout@v3
      - name: Run Command
        run: cd /home/moniyom/kw1_BingChilling_Infrastructure/ && bash run.sh
