name: Deploy Infrastructure to VPN Server

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  infrastructure_dir: "/home/moniyom/kw1_BingChilling_Infrastructure/"
  compose_file: "/home/moniyom/kw1_BingChilling_Infrastructure/compose.yaml"

jobs:
  deploy_Infra:
    runs-on: linux
    steps:
      - name: Run Deployment Script
        run: |
          # Enable "exit on error" behavior
          set -e

          # Navigate to the infrastructure directory
          cd ${{ env.infrastructure_dir }}  # Replace with the actual directory path

          # Pull the latest changes from the repository
          git pull

          # Start the Docker services defined in the specified compose file
          docker compose -f ${{ env.compose_file }} up -d --build # Replace with the actual compose file path

          # Provide feedback that the deployment process has started
          echo "Deployment process initiated."
