name: Deploy to VPN Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn
      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: ./vpn-st.ovpn
          username: 64130500014
          password: "!ManisocN20kmutt"
      - name: Deploy
        run: |
          ssh moniyom@$ip22kw1.sit.kmutt.ac.th "ls -al"
